# Generated by Django 5.1.5 on 2026-05-09 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_remove_contactus_submitted_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=200)),
                ('email_type', models.CharField(choices=[('checkout_today', 'Checkout Reminder - Today'), ('checkout_tomorrow', 'Checkout Reminder - Tomorrow'), ('booking_confirmation', 'Booking Confirmation'), ('payment_receipt', 'Payment Receipt')], max_length=30)),
                ('subject', models.CharField(max_length=300)),
                ('hotel_name', models.CharField(blank=True, max_length=200)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
