# Generated by Django 5.1.5 on 2026-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager')], max_length=100),
        ),
    ]
