# Generated by Django 5.1.5 on 2026-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
